export {
  default as authReducer,
  loginUser,
  signUpUser,
  logoutUser,
  getCurrentUser,
  updateUserProfile,
  clearError as clearAuthError,
  setUser,
  setSession,
  setLoading as setAuthLoading,
  clearAuth,
} from "./authSlice"

export {
  default as projectsReducer,
  fetchProjects,
  fetchProjectsForCurrentUser,
  fetchProjectDetails,
  createProject,
  updateProject,
  deleteProject,
  setCurrentProject,
  setSelectedProjectId,
  setViewMode,
  setFilters,
  clearFilters,
  clearError as clearProjectsError,
  updateProjectLocally,
  hydrateSelectedProjectFromStorage,
} from "./projectsSlice"

export {
  default as documentsReducer,
  fetchUserDocuments,
  hydrateSelectedDocumentFromStorage,
  setCurrentDocument,
  setSelectedDocumentId as setSelectedDocumentIdDocument,
  setCurrentSection,
  setEditingSection,
  setCommentsVisible,
  clearError as clearDocumentsError,
  updateSectionLocally,
  addSectionLock,
  removeSectionLock,
} from "./documentsSlice"

export {
  default as uiReducer,
  setCommentsPanelOpen,
  setSidebarOpen,
  hydrateCurrentViewFromStorage,
  toggleSidebar,
  toggleCommentsPanel,
  setCurrentView,
  openModal,
  closeModal,
  closeAllModals,
  removeModal,
  addNotification,
  hideNotification,
  removeNotification,
  setGlobalLoading,
  setLoading as setUiLoading,
  setBreadcrumbs,
  setTheme,
  setCompactMode,
  setGlobalSearch,
  setError,
  setFeature,
} from "./uiSlice"

export { default as pdfAnalysisApiReducer } from "./pdfAnalysisApiSlice"
